Avoid warnings with --coverage
Building with --coverage in CFLAGS causes gcc to raise a few new
maybe-uninitialized warnings:

src/ubik/ubikclient.c: In function ‘CallIter’:
src/ubik/ubikclient.c:395:3: error: ‘tc’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  (*aproc) (tc, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13,
  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     p14, p15, p16);
     ~~~~~~~~~~~~~~
[...]
src/afs/afs_pioctl.c: In function ‘PGetCacheSize’:
src/afs/afs_pioctl.c:3014:15: error: ‘flags’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     } else if (2 == flags){
               ^
[...]
src/butc/dump.c: In function ‘dumpPass’:
src/butc/dump.c:1078:58: error: ‘curDump’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   "Terminated while processing Volume %s (%u)\n", curDump->name,

It looks like none of these can actually reference uninitialized data
in practice, but initialize the relevant vars to avoid the warnings.

Change-Id: Ic3fb2850d280cee40b2f4810d35f786e3559b64d