AIX: Declare syscall()
We make direct syscalls in various places (to use AFS_SYSCALL), but
there is no prototype for syscall(). This causes errors when using the
clang-based xlc 17.1 on AIX, such as:

        .../src/volser/volmain.c:195:2: error: call to undeclared function 'syscall'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                syscall(AFS_SYSCALL /* AFS_SYSCALL */ , 28 /* AFSCALL_CALL */ , a3,
                ^

Declare a prototype for syscall() to avoid these errors.

Change-Id: Ica43e56e19f59155fe21fe8fdeb52525b2f678e9